### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by currenjin** [currenjin/high-level-rest-client-poc#1]
RestHighLevelClient (100%)
- [x] Opensearch 도메인 추가
- [x] Client Configuration 적용
- [x] Post 요청을 통한 Document 생성
- [x] Get 요청을 통한 Document 조회

RestHighLevelClient (66%)
- [x] Field 에 따른 조회 방법 Research
  - 필드 하나하나마다 커스텀해줘야 하는 불편함이 있음.
- [x] Field 에 따른 조회
- [ ] Field 에 일부 문자 포함 조회
